### ISSUE TITLE
more unix-friendly build system

### ISSUE THREAD

**Issue by pg83** [sgiurgiu/reddit_desktop#1]
Can you, please, provide cmake build system with fallbacks on pkg-config? vcpkg is not very common way of building software under unix, and without it there is no proper lib/cmake/* stuff for cmake package discovery.

**Comment by sgiurgiu** [comment]
With the latest commit ([a5b84f9](https://github.com/sgiurgiu/reddit_desktop/commit/a5b84f9b6dc8a1151f4a972e0409aed4d80aab7a)) we now support pkg-config packages on UNIX systems. Tested on Fedora 38 and FreeBSD 13.2 .
